services:
  backend:
    build: .
    container_name: integracao-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.afqmxqivndmxjfogffkg.supabase.co:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Corpcapsule13313
    restart: unless-stopped
