spring.datasource.url=jdbc:postgresql://db.afqmxqivndmxjfogffkg.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Corpcapsule13313
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
